#!/usr/bin/env bash

# A script that installs Nginx, sets up a basic configuration with a
#custom 404 page

# Update package lists
apt update

# Install Nginx
apt install -y nginx

# Define Nginx configuration file path
NGINX_CONF="/etc/nginx/sites-available/default"

# Configure Nginx to listen on port 80, serve "Hello World!", and set up a 
#custom 404 page
bash -c "cat > $NGINX_CONF" <<EOF
server {
    listen 80;
    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }

    # Custom 404 error page configuration
    error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
        root /var/www/html;
    }
}
EOF

# Create the HTML file to be served
bash -c "echo 'Hello World!' > /var/www/html/index.html"

# Create the custom 404 error page
bash -c "echo \"Ceci n'est pas une page\" > /var/www/html/custom_404.html"

# Restart Nginx without using systemctl
nginx -s reload

# Check if Nginx is running correctly
nginx -t
